### PR TITLE
How to reproduce

### PR DESCRIPTION
**Pull request by iasonsky**
- Added how to reproduce section for Equitune experiments
- Refactored jobfiles and jupyter notebooks
- Added .env file for wandb 
- Updated .yml file

### CODE REVIEW

**Review by mikhail-vlasenko — COMMENTED** [review]
lgtm, and i like the separation of wandb arguments, but I don't really have a clue about job files ¯\_(ツ)_/¯

**Comment by mikhail-vlasenko** [comment]
oh actually, should we remove the rest of the readme file that goes after our instructions?

its not really applicable anymore, and we can change citation info

**Comment by iasonsky** [comment]
> lgtm, and i like the separation of wandb arguments, but I don't really have a clue about job files ¯_(ツ)_/¯

yeah I really hope the git checkout works

**Comment by iasonsky** [comment]
> oh actually, should we remove the rest of the readme file that goes after our instructions?
> 
> its not really applicable anymore, and we can change citation info

sure

**Pull request merged**
